name: Go

on:
  workflow_dispatch:
  push:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        token: ${{ secrets.TEST_SECRET }}

    - name: Set up Go
      if: ${{ github.event_name == 'fork' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: set actor
      if: ${{ github.event_name != 'push' }}
      run: |
        touch abc.txt
        git config user.email "this@test"
        git config user.name ":robot: Human - automated testing"
        git add .
        git status
        git commit -m "this is a test commit"
        git push -u origin $(git branch --show-current) 
    - name: actor
      if: ${{ github.event.head_commit.author.name == 'Human - automated testing' }}
      run: echo "Success"
    - name: dd
      run: echo ${{ github.event.head_commit.author.name }}

