name: Go

on:
  workflow_dispatch:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      if: ${{ github.event_name == 'fork' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
