name: Go

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
      - test
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Testing
        run: |
          chmod -R +x ./.github/scripts
          echo ${{ github.event.before }}
          ./.github/scripts/test.sh
    
