name: Go

on:
  push:

  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: |
        CVPKG=$(go list ./... | grep -v "_test")CVPKG=$(go list ./... | grep -v "_test")
        go test -v -coverpkg $CVPKG ./...
