name: Go

on:
  workflow_dispatch:
  push:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        token: ${{ secrets.TEST_SECRET }}

    - name: Set up Go
      if: ${{ github.event_name == 'fork' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: set actor
      if: ${{ github.event_name != 'push' }}
      run: |
        token=$(echo -n $GITHUB_USER:${{ secrets.TEST_SECRET }} | base64)
        touch abc.txt
        git config user.name "Human - automated testing"
        git add .
        git status
        git commit -m "this is a test commit"
        git -c http.extraheaders="AUTHORIZATION: basic $token" push -u origin $(git branch --show-current) 
    - name: actor
      run: echo ${{ github.event.pusher.name }}

