name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      if: ${{ github.event_name == 'fork' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      if: ${{ github.event_name == 'fork' }}
      run: go build -v ./...

    - name: Build test list
      if: ${{ github.event_name == 'fork' }}
      run: CVPKG=$(go list ./... | grep -v "_test")
      
    - name: Test
      if: ${{ github.event_name == 'fork' }}
      run: go test -v -coverpackage $CVPKG ./...
      
  
