name: Go

on:
  pull_request:
    branches: 
      - main
      - test
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Build test list
      run: CVPKG=$(go list ./... | grep -v "_test")
      
    - name: Test
      run: go test -v -coverpackage $CVPKG ./...
      
  pull:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps: 
      - name: Echo
        run: |
          echo "This is a pull request" \
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: "testing"
          path: ${{ github.event_path }}
