name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      if: ${{ github.event_name == 'fork' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: actor
      run: |
       echo ${{ github.actor }} \
       echo ${{ github.actor.login }} \
       echo ${{ github.actor.display_login }} 
      
   
