name: Go

on:
  workflow_dispatch:
  push:
  
env:
  SKIP: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        token: ${{ secrets.TEST_SECRET }}

    - name: Set up Go
      if: ${{ github.event_name == 'fork' }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: set actor
      if: ${{ github.event_name != 'push' }}
      run: |
        touch abc.txt
        echo a >> abc.txt
        git config user.email "this@test"
        git config user.name ":zap: Human - automated testing"
        git add .
        git status
        git commit -m "this is a test commit [automation]"
        git push -u origin $(git branch --show-current) 
    - name: actor
      if: "${{ contains(github.event.head_commit.message, '[automation]') }}"
      run: |
        echo "Success"
        echo $SKIP
    - name: dd
      run: SKIP=true

