name: Go2

on:
  pull_request:
    types: [ labeled ]
  

jobs:
  pull:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps: 
      - name: Echo
        run: |
          echo "This is a pull request" \
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: "testing"
          path: ${{ github.event_path }}
