name: Go2

on:
  pull_request:
   #types: [ labeled ]
  

jobs:
  pull:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps: 
      - name: Echo
        run: |
          echo "This is a pull request" 
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \ 
          -H "Authorization: token ${{ secrets.TEST_SECRET }}" \
          https://api.github.com/repos/gorewiczMark/learnblockchain/issues/10/labels \
          -d '{"labels":["bug"]}'
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: "testing"
          path: ${{ github.event_path }}
